name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run next lint
        run: yarn run lint

      - name: Run prettier check
        run: yarn run prettier:check